# Handling shape

In [2]:
import numpy as np

### reshape
```
Array의 shape의 크기를 변경함 _ element의 갯수는 동일
```

In [4]:
test_matrix = [[1,2,3,4],[1,2,5,7]]
np.array(test_matrix).shape

(2, 4)

In [5]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 7])

In [6]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [8]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [11]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [12]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 7]]])

In [13]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [16]:
test_matrix = [[[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])