# ndarray

In [30]:
import numpy as np

In [5]:
test_array = np.array([2,3,4,"5"], float)
# String Type의 데이터를 입력해도
# Float Type으로 자동 형변환을 실시
# Array(배열) 전체의 데이터 Type을 반환함 # Array(배열) 의 shape을 반환함

In [6]:
test_array
#정수, String 으로 저장해도 float 형식으로 저장하여 float 형식의 array가 됨

array([2., 3., 4., 5.])

In [7]:
type(test_array[1])

numpy.float64

In [8]:
test_array = np.array([1,2,3,4,"8"], np.float32)
test_array

array([1., 2., 3., 4., 8.], dtype=float32)

In [9]:
test_array.dtype

dtype('float32')

In [10]:
test_array.shape
# shape : numpy array의 object의 dimension 구성을 반환함
# dtype : numpy array의 데이터 type을 반환함

(5,)

In [11]:
np.array([[1,3,4,5,'8']]).shape
#(1,5)
# 1 -> row를 의미
# 5 -> row의 각 단위 
# 큰 단위에서 작은 단위로
# 새로 생긴 것이 앞에 생성되는 개념

(1, 5)

In [12]:
np.array([[1,1,1,1,1,1] , [1,1,1,1,1,1] , [1,1,1,1,1,1] , [1,1,1,1,1,1]]).shape
# (4, 6)
# 4개의 row가 생성되고
# 각 6개의 값이 있음

(4, 6)

In [13]:
np.array([[[1,1,1,1,1] , [1,1,1,1,1], [1,1,1,1,1]],
          [[1,1,1,1,1] , [1,1,1,1,1], [1,1,1,1,1]],
          [[1,1,1,1,1] , [1,1,1,1,1], [1,1,1,1,1]],
          [[1,1,1,1,1] , [1,1,1,1,1], [1,1,1,1,1]],
         ]).shape
#(4, 3, 5)
#4개의 3x5 행렬의 값
#3개의 row
#5개의 데이터

(4, 3, 5)

In [26]:
test_array = np.array([1,2,3,4,5,6,7,8], float)
print(test_array)
test_array.shape
#vector , array 1차원 배열
#(8,) 값이 8개

[1. 2. 3. 4. 5. 6. 7. 8.]


(8,)

In [21]:
matrix = [[1,2,3,4],[5,6,7,8],[9,1,2,3]]
print(matrix)
np.array(matrix, int).shape
#matrix , 2차원 배열
#(3,4)
#row가 3개
#값이 4개

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]]


(3, 4)

In [31]:
tensor = [[[1,2,3,4],[5,6,7,8],[9,1,2,3]],
          [[1,2,3,4],[5,6,7,8],[9,1,2,3]],
          [[1,2,3,4],[5,6,7,8],[9,1,2,3]],
          [[1,2,3,4],[5,6,7,8],[9,1,2,3]]]
print(tensor)
np.array(tensor, int).shape
#tensor, 3차원 배열,
#(4,3,4)
#matrix 가 4개
#row 가 3개
# index가 4개

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]]]


(4, 3, 4)

In [33]:
#Ndarray의 single element가 가지는 data type
#각 element가 차지하는 memory의 크기가 결정됨
np.array([[1,2,3,], [4.5, 5, 6]], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
print(np.array(tensor,int).ndim)
print(np.array(tensor,int).size)

3
48


In [41]:
np.array([[1,2,3], [4,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.array([[1,2,3],[4,5,6]], dtype=np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [53]:
print(np.array([[1,2,3],[4,5,6]], dtype=np.float32).nbytes)
print(np.array([[1,2,3],[4,5,6]], dtype=np.int8).nbytes)
print(np.array([[1,2,3],[4,5,6]], dtype=np.float64).nbytes)

24
6
48
